FROM php:5.6.31-fpm-alpine

WORKDIR /opt

COPY --from=composer:1.6 /usr/bin/composer /usr/bin/composer

RUN /usr/bin/composer global require hirak/prestissimo

COPY composer.json /opt
COPY composer.lock /opt

